// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function normalizeEnv(value: string | undefined) {
  return value?.trim().replace(/^['\"]|['\"]$/g, '');
}

function looksLikePublishableKey(key: string) {
  return key.startsWith('sb_publishable_') || key.startsWith('sb_anon_');
}

function looksLikeLegacyJwt(key: string) {
  return key.startsWith('eyJ') && key.split('.').length === 3;
}

function readJwtRole(key: string) {
  if (!looksLikeLegacyJwt(key)) return undefined;
  try {
    const payload = JSON.parse(Buffer.from(key.split('.')[1], 'base64url').toString('utf8')) as { role?: string };
    return payload.role;
  } catch {
    return undefined;
  }
}

function looksLikeSecretKey(key: string) {
  // Supabase projects may expose either a newer sb_secret_* key or an older JWT service_role key.
  return key.startsWith('sb_secret_') || readJwtRole(key) === 'service_role';
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = normalizeEnv(process.env.SUPABASE_URL);
  const SUPABASE_SERVICE_ROLE_KEY = normalizeEnv(process.env.SUPABASE_SERVICE_ROLE_KEY);

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase server environment variable(s): ${missing.join(', ')}. Add them in Vercel without VITE_ prefix, then redeploy.`;
    console.error(`[Supabase Admin] ${message}`);
    throw new Error(message);
  }

  if (looksLikePublishableKey(SUPABASE_SERVICE_ROLE_KEY) || !looksLikeSecretKey(SUPABASE_SERVICE_ROLE_KEY)) {
    const message = 'Invalid SUPABASE_SERVICE_ROLE_KEY. Admin user creation/reset/delete needs the server-only Supabase service_role/secret key, not the publishable/anon key. Add it only as SUPABASE_SERVICE_ROLE_KEY in Vercel and redeploy.';
    console.error(`[Supabase Admin] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
